### ISSUE TITLE
Demon Helmet Price on Wulkan

### ISSUE THREAD

**Issue by peterramaldes** [Dreamshade-1911/dreamloot#3]
Hey, could you add the price for Demon Helmet on Wulkan? [According this wiki](https://wiki.mediviastats.info/Demon_Helmet), cost 45k on Wulkan

**Comment by peterramaldes** [comment]
@Dreamshade-1911 I also created a PR for this: https://github.com/Dreamshade-1911/dreamloot/pull/4

**Comment by Dreamshade-1911** [comment]
Done :)
